- contents_motif.svg
- cut.mli
- cut.mll
- hacha.ml
- install.sh
- next_motif.svg
- previous_motif.svg
This small PR adds three svg variants to the previous/up/next arrows used by hacha, and a corresponding command line flag `-svg-arrows`.  The svg arrows themselves are quite minimalist to go with the flat design trend.
> Svg arrows

- README
Je suppose que l'auteur souhaitait dire "avertissement" en anglais, mais "advertisement" signifie "publicité".
Je propose de remplacer "advertisement" par "note", qui signifie "remarque".
Je propose aussi de supprimer la ligne vide sous "Note" pour devenir cohérent avec le reste du README (pas de ligne vide sous les sous-titres).
> Fix (not so) critical bug in README

- html/hevea.hva
The old way to handle `\marginpar` in HTML is to insert `div`-elements that
tear apart paragraphs.  Moreover, the marginal text does not end up in the
margins but gets squeezed into a box at the side of the body text.
This P/R replaces the `div` with `span` and adjusts the CSS part to get an
HTML layout that is much closer to the LaTeX layout (at least of "article.cls").
(As is, the new `\marginpar`s can serve as a base for implementing marginal
notes (aka sidenotes) that completely replace `\footnote`s in a web page.)
> Reimplement the HTML handling of \marginpar

- ragged2e.hva
LaTeX package ragged2e implements macro \justifying and environment justify
to switch back from its ragged-left and ragged-right modes.  This P/R implements
the same functionality for HTML with the help of `text-align`-mode `justify`.
BTW, to move Hevea's layout closer to LaTeX's _default_ `text-align: justify` can
to go into the CSS element for `body`.
> Implement macro \justifying and environment justify

- html/hevea.hva
Reverts maranget/hevea#14
Sorry I merged too fast, before noticing that this PR changes the default rendering of _all_ pages produced, adding 20% margin on both sides. I disagree that all hevea output is changed.
> Revert "Reimplement the HTML handling of \marginpar"

- hyperref.hva
Some "starred" reference macros are missing from the Hyperref-compatibility
package _hyperref.hva_.  Add them. 
En passant add `\autopageref` in a way compatible with `\pageref`.
> Hyperref: add some starred macros

- html.ml
- html/hevea.hva
- latexscan.mll
- outManager.mli
- text.ml
Introduce a novel type of block: `span@inline@block`.
Its semantics are tailor made to meet the processing expectations of
`\marginpar`; implement Hevea's `\marginpar` with the help of
`span@inline@block`.
Slightly adjust the style of marginpars:
- Add a small bottom margin to prevent multiple borders from bumping
into each other (margin-bottom:1ex).
- Instruct all marginpar-boxes to clear to the same side as the
initial one (clear:left and clear:right).
Here is a small example that can be used to visualize the changes:
```latex
aaaaaaaa bbbbbbbb
cccccccc dddddddd
eeeeeeee ffffffff
gggggggg hhhhhhhh
iiii\marginpar{IIII}iiii jjjj\marginpar{JJJJ}jjjj
kkkk\marginpar{KKKK}kkkk llll\marginpar{LLLL}llll
mmmmmmmm nnnnnnnn
oooooooo …
```
> Introduce a novel type of block to implement \marginpar.

- articlecommon.hva
- bookcommon.hva
- doc/text.tex
Documentclass `article` puts the abstract into a separate CSS-class.
The patch extends this behavior to class `book` (and thus `report`).
Along the way the special case of an empty `\abstractname` is handled.
The documentation is updated to reference *all* CSS-classes that
are responsible for marking up a titlepage.
> Consistent handling of title-page "abstract" 

- latexcommon.hva
This PR aligns equation numbers flush to the right (default) or the
left (document option "leqno") margin similar to LaTeX.
Here is an example source file to try the change:
```latex
\documentclass[]{article}% try option: `leqno'
\ifhevea
\renewcommand{\vec}[1]{\mathbf{#1}}
\fi
\newif\ifnabla\nablafalse
\newcommand*{\grad}{\ifnabla\ensuremath{\nabla}\else\mbox{grad}\fi}
\renewcommand*{\div}{\ifnabla\ensuremath{\nabla \cdot}\else\mbox{div}\fi}
\newcommand*{\curl}{\ifnabla\ensuremath{\nabla \times}\else\mbox{curl}\fi}
%%  Comment-out to get default layout.
\newstyle{body}{margin: auto; max-width: 36em; width: 60\%}
%%  Uncomment to revert to old behavior.
%\newstyle{.equationnumber}{float: none; left: 2em; position: relative; right: auto} …
```
> Aligned equation numbers

- doc/text.tex
- html/hevea.hva
Make the translations of `quote` and `quotation` faithfully follow LaTeX
and implement the `verse`-environment.
The CSS-code for `verse` already uses the upcoming extension of the
`text-indent` property
```
hanging each-line
```
which duplicates the LaTeX behavior of indenting wrapped lines,
i.e., should be exactly what we need.  See
https://www.w3.org/TR/css-text-3/#text-indent-property
and also
https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent
In all three cases the documentation has been updated or extended
according to the changes.
> Improve "quote" and "quotation".  Implement "verse".

- doc/text.tex
- outUnicode.ml
- outUnicode.mli
- verb.mll
Associate `\verb` and `\verb*` (which translate into `code` elements)
with CSS class `verb`.
In `\verb*` and in `verbatim*` environments use the Unicode
"visible space" character to indicate spaces or tabs instead of
an ASCII underscore.
> CSS class for \verb and visual spaces for starred versions

- html/hevea.hva
- verb.mll
A HTML-generation bug has been introduced with #34 
Problem: 
```ocaml
Dest.open_group "code class=\"verb\""
```
constructs the HTML group
```html
<code class="verb">
...
</code class="verb">
```
which is invalid HTML as closing elements never have attributes.
Solution: Use `Dest.open_block` which allows to pass an attribute.
En passant: Associate `\verb` with CSS-class `verb` via `\setenvclass`.
> Fix HTML-generation bug introduced in P/R #34

- latexcommon.hva
These definitions arose serendepitously from looking at CSS property ```visibility```
recalling the superficial similarity of ```\makebox``` with CSS ```inline-block```.
Working example:
```latex
\usepackage{parskip}
\newstyle{body}{%
margin: auto;
max-width: 32em;
line-height: 100\%;
text-align: justify;
width: 55\%;
}
\section{\textbackslash phantom}
ABC.
A\phantom{B}C.
\section{\textbackslash hphantom}
$$
\begin{array}{l}
Side Middle Side  \\
S\hphantom{ide\ }M\hphantom{iddle\ }Side  \\
\end{array}
$$
\section{\textbackslash vphantom}
Without \verb+\vphantom+:
$$
\sqrt{a}\cdot\sqrt{a^3}
$$
With \verb+\vphantom+:
$$
\sqrt{\vphantom{a^3}a}\cdot\sqrt{a^3}
$$
\section{\textbackslash smash}
To demonstrate the effect of smash we …
```
> Introduce the macros `\phantom', `\hphantom', `\vphantom', and `\smash'.

- imakeidx.hva
- index.ml
Fix "multiple label definition" bug in \@printindex and \printindex
that was introduced in P/R #18
Macros `\@printindex` and `\printindex` of package _imakeidx.hva_ define the
label `section@the@hevea@index`.  Multiple indices generate multiple
definitions for this label.  The result is an invalid HTML file.
This patch fixes the problem by appending the index name to the label,
which results in `section@the@hevea@index@default` for the default
case.
Found by **xmllint**.
> Fix HTML-generation bug introduced in P/R #18

- latexcommon.hva
Hevea lacks the `\discretionary` macro which means words that need
it (on the LaTeX side) get butchered in the HTML output.  This P/R
implements just as much of
```tex
\discretionary{pre-break}{post-break}{no-break}
```
that the special cases `\discretionary{}{}{}` (empty discretionary) and
`\discretionary{-}{}{}` (simple hyphenation point) are covered and all
others simply expand to `no-break`.
Mapping of the empty discretionary to "word-break opportunity":
Some browser interpret the zero-width space character, some the HTML5
tag `wbr`, and presumable others do not understand either.  So, we have
introduced an extra level of indirection called `\word@break@opportunity`,
which can be redefined by the user to get the desired translation of
`\discretionary{}{}{}`.  The default is `wbr`.
TeX …
> Emulate "\discretionary" and implement "\-".

- html/book.hva
> Drop non-breaking space (TeX: `~') if chaptername is empty.

- htmlCommon.ml
Add missing length units `px` and `pt` to HtmlCommon.put_length.
Found by **vnu** checker, which also is the engine behind
the [W3C Markup Validation Service](https://validator.w3.org/).
> Add some missing length units

- doc/text.tex
- html.ml
- html/hevea.hva
- htmlCommon.ml
- htmlMath.ml
- iso-symb.hva
- winfonts.hva
In the aftermath of P/R "Add some missing length units" (#44) Luc suggested
to document the CSS class that controls the appearance of horizontal bars
generated with the internal (and documented) macro `\@hr`.  We agreed on
renaming the class to `horizontal-rule` before exposing it to the Hevea users.
For consistency class `vertical-rule` has been renamed, too.
> Document CSS class `horizontal-rule`.

- amsmath.hva
- doc/text.tex
- html/hevea.hva
- latexcommon.hva
- package.ml
Add `\makebox[WIDTH][ALIGN]{TEXT}` and `\framebox[WIDTH][ALIGN]{TEXT}`
with most of their LaTeX functionality.  Base the new definition
of `\fbox` on `\framebox`.  Alignment type `s` is unimplemented.
Macro `\mbox` is not touched.
Here is a demo-document:
```latex
\newenvironment{markerbar}{\begingroup$|$}{$|$\endgroup}
\section{Text Mode}
\begin{itemize}
\item \texttt{\textbackslash mbox}:
\mbox{typeset text in LR-mode};
\item \texttt{\textbackslash makebox}
\begin{itemize}
\item without optional arguments:
\begin{markerbar}\makebox{text in LR-mode}\end{markerbar};
\item with fixed width:
\begin{markerbar}\makebox[12em]{text in LR-mode}\end{markerbar};
\begin{markerbar}\makebox[12em][c]{text in LR-mode}\end{markerbar};
\item …
```
> Implement \makebox and \framebox; re-implement \fbox.

- html.ml
- html/hevea.hva
- htmlCommon.ml
- htmlMath.ml
Alternative title: _"The Optimizer Strikes Back!"_
The current definition of CSS class `horizontal-rule` sets both
`height` and `width`.  Macro `\@hr` uses class `horizontal-rule`,
but overrides `height` and `width` with a `style` attribute to
control the shape of the rule as requested by the macros'
actual arguments.
If the optimizer decides to hoist this `style` and
convert it to a CSS class the precedence rules change:
Classes are applied in their order of definition.  The optimizer
sorts all classes into alphabetical order and uses the prefix `c`
for its own classes.  That way the style hoisted into class `c###`
always ends up before class `horizontal-rule` and the style's
`height` and `width` thus are shadowed.
The last item of the following example generates different
horizontal …
> Remove `height` and `width` from class `horizontal-rule`

- html/hevea.hva
- hyphenat.hva
- iso-symb.hva
- latexcommon.hva
- latexscan.mll
- outUnicode.ml
- outUnicode.mli
- spaces.hva
- text/color.hva
- text/hevea.hva
- verb.mll
Some of my previous extensions to the HTML generation neglected
the GNU Info and Plain Text output.  #34 is particularly gross in that
it introduces an uncaught exception for the perfectly valid LaTeX
code ``\verb*+ +``.  This P/R plugs many other leaks that sneaked
in e.g. with #23 and #35.
I rose to the occasion and implemented e.g. environment ``divstyle``
and macros ``\colorbox``, ``\fcolorbox`` as "dumb" expansions that
simply replicate their _TEXT_ contents/arguments.  This cleans up
text output nicely.
If somebody finds missing environments or macros for GNU Info or
Plain Text output please touch base with me so that we can get this
stuff out of the way.
> Synchronize GNU Info and Plain Text output with HTML output.

- doc/text.tex
- html/hevea.hva
- latexcommon.hva
- package.ml
Implement macro `\rule` with SVG.  Its properties nicely match
the LaTeX original as it is rendered inline and zero-width width
or height lead to an invisible "strut".
Try it for example with
```latex
\newenvironment{markerbar}{\begingroup$|$}{$|$\endgroup}
\section{Rules}
\texttt{\textbackslash rule}; size is indicated as width/height and
optionally followed by a signed offset.
\begin{itemize}
\item 10em/0.0625em: \rule{10em}{0.0625em}
\item 1em/1em: \rule{1em}{1em}
\item 0.0625em/3em: \rule{0.0625em}{3em}
\item 50\% linewidth/2pt: \rule{0.5\linewidth}{2pt}
\end{itemize}
\noindent Struts (zero width or zero height) -- extents indicated with marker bars
\begin{itemize}
\item 10em/0pt: …
```
> SVG-based macro \rule

- doc/text.tex
- html/hevea.hva
- latexcommon.hva
Floating tables and figures are both decorated by `\@figrule` which reads
unintuitively for tables.  Therefore, this P/R renames `\@figrule` to `\@floatrule`.
The `hr` elements this macro controls get associated with CSS class `floatrule`.
Moreover, users can override the rule generation completely by defining
`\floatseparator`.  An empty expansion of `\floatseparator` recovers the
original LaTeX layout.  The P/R documents all the user-visible macros and
classes.
As footnotes are also a (special) kind of float document them in the relevant
section of the reference manual, too.
> Flexible float decoration

- Makefile
- cut.mll
- foot.ml
- htmlCommon.ml
- htmllex.mll
- htmltext.ml
- index.ml
- latexmacros.ml
- latexscan.mll
- misc.ml
- package.ml
- pp.ml
- section.ml
- subst.mll
- text.ml
- ultra.ml
- verb.mll
This PR replaces the deprecated functions that were removed in OCaml 5 by their OCaml ≥4.08 equivalent.
It also sneakily enable the deprecation warning.
> OCaml 5 support: remove uses of deprecated functions

- doc/text.tex
> [doc] Precise comment equivalents usage

- html/fancyvrb.hva
Notice that most keyval settings in the optional argument are not recognized.
> Package fancyvrb, command \VerbatimInput optional argument.

- bugs/015/a.tex
- verb.mll
- version.ml
Bug fix. The following code failed:
```
% cat a.tex
\usepackage{comment}
\excludecomment{whenBuildMayDay2025Int}
\begin{whenBuildMayDay2025Int}
Conditional text comes here
\end{whenBuildMayDay2025Int}
\end{document}
% /bin/hevea -fix -O a.tex
Exclude comment 'comment'
Exclude comment 'whenBuildMayDay2025Int'
./a.tex:10: Warning: Command not found: \endwhenBuildMayDay
Fixpoint reached in 1 step(s)
```
Fix consists in using the `\csname ... \endcsname` construct for scanning the `\end...` command at the end
of excluded comment scanning.
> [hevea] Fix end comment
